import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={false}>
      <body className={inter.className} suppressHydrationWarning={false}>
        <Header />
        <main className="py-6 px-4 sm:px-12">
        <Provider>
          {children}
        </Provider>
        </main>
      </body>
    </html>
  );
}
